spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springboot
    driver-class-name: org.mariadb.jdbc.Driver
    username: springboot
    password: springboot1234

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.example.board: INFO
    org.hibernate.SQL: WARN
